'use client';

import { Globe, FileText, Sparkles, Zap, ArrowRight, Image, Palette } from 'lucide-react';

interface EntryChoiceStepProps {
  onChooseURL: () => void;
  onChooseManual: () => void;
  onChooseBackground?: () => void;
}

export function EntryChoiceStep({ onChooseURL, onChooseManual, onChooseBackground }: EntryChoiceStepProps) {
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 rounded-full text-primary text-sm font-medium">
          <Sparkles className="w-4 h-4" />
          AI-Powered Ad Creation
        </div>
        <h1 className="text-2xl md:text-3xl font-bold tracking-tight">
          How would you like to get started?
        </h1>
        <p className="text-muted-foreground max-w-md mx-auto">
          Choose the path that works best for you. Both lead to stunning, 
          professional ads generated by AI.
        </p>
      </div>

      {/* Choice Cards */}
      <div className="grid md:grid-cols-3 gap-6 mt-8">
        {/* Option A: Website URL */}
        <button
          onClick={onChooseURL}
          className="group relative flex flex-col items-start p-6 bg-gradient-to-br from-primary/5 to-primary/10 border-2 border-primary/20 rounded-2xl text-left transition-all duration-300 hover:border-primary/50 hover:shadow-lg hover:shadow-primary/10 hover:-translate-y-1"
        >
          {/* Recommended Badge */}
          <div className="absolute -top-3 left-6 px-3 py-1 bg-primary text-primary-foreground text-xs font-semibold rounded-full">
            ⚡ Fastest
          </div>
          
          {/* Icon */}
          <div className="flex items-center justify-center w-14 h-14 bg-primary/10 rounded-xl mb-4 group-hover:bg-primary/20 transition-colors">
            <Globe className="w-7 h-7 text-primary" />
          </div>

          {/* Content */}
          <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
            I have a website
            <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all" />
          </h3>
          
          <p className="text-muted-foreground text-sm mb-4">
            Enter your website URL and our AI will automatically extract your 
            brand identity, colors, logo, and products.
          </p>

          {/* Features */}
          <ul className="space-y-2 text-sm">
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-primary" />
              Auto-detect brand colors & logo
            </li>
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-primary" />
              Extract products automatically
            </li>
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-primary" />
              AI analyzes your tone & style
            </li>
          </ul>

          {/* Time estimate */}
          <div className="mt-4 pt-4 border-t border-primary/10 w-full">
            <span className="text-xs text-muted-foreground">
              Setup time: <span className="text-primary font-medium">~1 minute</span>
            </span>
          </div>
        </button>

        {/* Option B: Manual Entry */}
        <button
          onClick={onChooseManual}
          className="group relative flex flex-col items-start p-6 bg-muted/30 border-2 border-border rounded-2xl text-left transition-all duration-300 hover:border-primary/30 hover:shadow-lg hover:-translate-y-1"
        >
          {/* Icon */}
          <div className="flex items-center justify-center w-14 h-14 bg-muted rounded-xl mb-4 group-hover:bg-primary/10 transition-colors mt-3">
            <FileText className="w-7 h-7 text-muted-foreground group-hover:text-primary transition-colors" />
          </div>

          {/* Content */}
          <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
            Enter details manually
            <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all" />
          </h3>
          
          <p className="text-muted-foreground text-sm mb-4">
            Describe your business, upload your assets, and let AI create 
            ads based on your input.
          </p>

          {/* Features */}
          <ul className="space-y-2 text-sm">
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-muted-foreground/50" />
              Full control over all details
            </li>
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-muted-foreground/50" />
              No website required
            </li>
            <li className="flex items-center gap-2 text-muted-foreground">
              <Zap className="w-4 h-4 text-muted-foreground/50" />
              Great for new businesses
            </li>
          </ul>

          {/* Time estimate */}
          <div className="mt-4 pt-4 border-t border-border w-full">
            <span className="text-xs text-muted-foreground">
              Setup time: <span className="font-medium">~5 minutes</span>
            </span>
          </div>
        </button>

        {/* Option C: Background Only (No Text) */}
        {onChooseBackground && (
          <button
            onClick={onChooseBackground}
            className="group relative flex flex-col items-start p-6 bg-gradient-to-br from-violet-500/5 to-purple-500/10 border-2 border-violet-500/20 rounded-2xl text-left transition-all duration-300 hover:border-violet-500/50 hover:shadow-lg hover:shadow-violet-500/10 hover:-translate-y-1"
          >
            {/* 4K Badge */}
            <div className="absolute -top-3 left-6 px-3 py-1 bg-gradient-to-r from-violet-500 to-purple-500 text-white text-xs font-semibold rounded-full">
              🎨 For Designers
            </div>
            
            {/* Icon */}
            <div className="flex items-center justify-center w-14 h-14 bg-violet-500/10 rounded-xl mb-4 group-hover:bg-violet-500/20 transition-colors mt-3">
              <Image className="w-7 h-7 text-violet-500" />
            </div>

            {/* Content */}
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2">
              Background Only
              <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all" />
            </h3>
            
            <p className="text-muted-foreground text-sm mb-4">
              Generate a stunning 4K marketing background without any text. 
              Perfect for designers who want to add their own typography.
            </p>

            {/* Features */}
            <ul className="space-y-2 text-sm">
              <li className="flex items-center gap-2 text-muted-foreground">
                <Palette className="w-4 h-4 text-violet-500" />
                4K ultra-high resolution
              </li>
              <li className="flex items-center gap-2 text-muted-foreground">
                <Palette className="w-4 h-4 text-violet-500" />
                No text - pure visuals
              </li>
              <li className="flex items-center gap-2 text-muted-foreground">
                <Palette className="w-4 h-4 text-violet-500" />
                Product image optional
              </li>
            </ul>

            {/* Time estimate */}
            <div className="mt-4 pt-4 border-t border-violet-500/10 w-full">
              <span className="text-xs text-muted-foreground">
                Generation time: <span className="text-violet-500 font-medium">~30 seconds</span>
              </span>
            </div>
          </button>
        )}
      </div>

      {/* Bottom info */}
      <p className="text-center text-sm text-muted-foreground">
        Both options use the same powerful AI to generate your ads. 
        <br className="hidden md:block" />
        Choose based on whether you have an existing website.
      </p>
    </div>
  );
}
